import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  tr: {
    // Header
    'header.title': 'MGL Digital AI',
    'header.login': 'Giriş / Kayıt',
    'header.logout': 'Çıkış Yap',
    'header.opportunities': 'Fırsatları Keşfet',
    'header.welcome': 'Hoş geldiniz',

    // Hero Section
    'hero.title': 'Stratejiyle Dönüşüm Sağlıyoruz.',
    'hero.subtitle': 'Reklam ve İş Süreçlerinizi AI Agent ile Otomatikleştirerek. Sadece "tıklama" değil, gerçek "sonuç" getiriyoruz.',
    'hero.cta.opportunities': 'AI ile Fırsatları Keşfet',
    'hero.cta.demos': 'Canlı Demoları Gör',

    // Benefits Section
    'benefits.title': 'Sadece Çalışmak Değil, Akıllı Çalışmak',
    'benefits.subtitle': 'Her gün aynı işleri tekrar tekrar yapmaktan yoruldunuz mu? İşte size zaman, para ve müşteri kazandıracak çözümler:',
    'benefits.time.title': 'Zaman Tasarrufu',
    'benefits.time.desc': 'Günde 3-4 saat manuel işten kurtulun',
    'benefits.sales.title': 'Satış Artışı',
    'benefits.sales.desc': 'Otomatik takip ile %40 daha fazla satış yakalayın',
    'benefits.error.title': 'Hata Azaltma',
    'benefits.error.desc': 'İnsan hatası sıfıra iner, her şey kusursuz çalışır',
    'benefits.satisfaction.title': 'Müşteri Memnuniyeti',
    'benefits.satisfaction.desc': '7/24 anında yanıt ile mutlu müşteriler yaratın',

    // Services Section
    'services.title': 'Tek Bir Merkez, Sınırsız Yetenek',
    'services.subtitle': 'Stratejiden tasarıma, reklamdan otomasyona, tüm dijital ihtiyaçlarınız için buradayız.',
    'services.ads.title': 'AI Destekli Reklam Yönetimi',
    'services.ads.desc': 'Meta & Google reklam kampanyalarınızı, sürekli öğrenen yapay zeka algoritmalarıyla yöneterek bütçenizi en verimli şekilde kullanıyoruz.',
    'services.ads.integration': 'Reklamdan gelen her potansiyel müşteriyi AI Chatbot veya Sesli Asistan ile anında karşılıyoruz.',
    'services.automation.title': 'AI Agent & Otomasyon Kurulumu',
    'services.automation.desc': 'WhatsApp, E-posta, Telefon ve web siteniz için 7/24 çalışan, randevu alan, bilgi veren ve veri toplayan akıllı asistanlar tasarlıyoruz.',
    'services.automation.integration': 'Kurduğumuz otomasyonları beslemek için en doğru müşteri adaylarını getiren reklam kampanyaları planlıyoruz.',
    'services.web.title': 'Dönüşüm Odaklı Web Tasarımı',
    'services.web.desc': 'Sadece güzel değil, aynı zamanda bir müşteri kazanma makinesi olarak çalışan modern ve hızlı web siteleri inşa ediyoruz.',
    'services.web.integration': 'Tasarladığımız her siteye, ziyaretçilerinizi müşteriye dönüştürecek interaktif Canlı Demo modülleri ve Chatbot\'lar entegre ediyoruz.',

    // Demos Section
    'demos.title': 'Anlatmıyoruz, Gösteriyoruz.',
    'demos.subtitle': 'Aşağıdaki demoları deneyin ve "acaba benim şu işim de otomatik olabilir mi?" diye düşünün:',
    'demos.whatsapp.title': 'Birebir Strateji Görüşmesi',
    'demos.whatsapp.desc': 'Otomasyon fikirlerinizi doğrudan kurucumuz Mustafa Bey ile görüşmek için WhatsApp üzerinden anında iletişime geçin.',
    'demos.email.title': 'Otomatik E-posta Dizisi',
    'demos.email.desc': 'Web sitenizdeki formu dolduran herkese anında kişiselleştirilmiş bir e-posta gönderin.',
    'demos.phone.title': 'AI Sizi Arasın',
    'demos.phone.desc': 'Numaranızı bırakın, AI sesli asistanımız sizi arayarak yeteneklerini sergilesin.',
    'demos.contact': 'İletişime Geç',
    'demos.live': 'Canlı Demo',
    'demos.data.title': 'Manuel Veri Aktarımı',
    'demos.data.desc': 'Excel\'den CRM\'e sürekli kopyala-yapıştır mı yapıyorsunuz? Bu süreci tamamen ortadan kaldırın.',
    'demos.reports.title': 'Haftalık Rapor Çilesi',
    'demos.reports.desc': 'Her hafta farklı platformlardan veri toplayıp rapor hazırlamak saatlerinizi mi alıyor?',
    'demos.onboarding.title': 'Yeni Çalışan Süreçleri',
    'demos.onboarding.desc': 'İşe yeni başlayanlara belgeleri tek tek mi veriyorsunuz? Tüm süreci tek tıkla otomatik başlatın.',

    // Strategy Section
    'strategy.title': 'Başarı Tesadüf Değildir.',
    'strategy.subtitle': 'Her adımı ölçülebilir veriye dayanan, kanıtlanmış bir stratejiyle hareket ediyoruz.',
    'strategy.funnel': 'Funnel Stratejimiz',
    'strategy.kpi': 'KPI Takibimiz',

    // CTA Section
    'cta.title': 'Hazır mısınız? İşinizi Birlikte Dönüştürelim!',
    'cta.subtitle': 'Hangi manuel işlerinizin otomatikleştirilebileceğini ve reklam bütçenizi nasıl daha verimli kullanabileceğinizi öğrenmek için 2 dakikada size özel bir analiz sunalım.',
    'cta.analysis': 'Ücretsiz Otomasyon Analizi Al',
    'cta.products': 'Otomasyon Satın Al',

    // Products Page
    'products.title': 'Otomasyon Çözümleri',
    'products.subtitle': 'İşletmeniz için özel olarak tasarlanan AI otomasyon sistemleri',
    'products.back': 'Ana Sayfaya Dön',
    'products.buy': 'Satın Al',
    'products.subscribe': 'Abonelik Başlat',

    // Auth
    'auth.login': 'Hesabınıza Giriş Yapın',
    'auth.signup': 'Hesap Oluşturun',
    'auth.email': 'E-posta Adresi',
    'auth.password': 'Şifre',
    'auth.confirmPassword': 'Şifre Tekrarı',
    'auth.loginButton': 'Giriş Yap',
    'auth.signupButton': 'Hesap Oluştur',
    'auth.switchToSignup': 'Kayıt Olun',
    'auth.switchToLogin': 'Giriş Yapın',
    'auth.forgotPassword': 'Şifremi Unuttum',

    // Chatbot
    'chatbot.title': 'AI Asistan',
    'chatbot.subtitle': 'Genellikle anında yanıt verir',
    'chatbot.placeholder': 'Mesajınızı yazın...',
    'chatbot.greeting': 'Merhaba! Size nasıl yardımcı olabilirim?',
    'chatbot.button': 'AI Chatbot\'u Deneyin',

    // Footer
    'footer.title': 'AI Otomasyon Ajansı - İşinizi Geleceğe Taşıyoruz',
    'footer.company': 'MGL DIGITAL MEDIA LTD',
    'footer.registered': 'Registered in England and Wales. Company Number: 16007414',
    'footer.office': 'Registered Office',
    'footer.address': '112 Bertram Road, Enfield, England, EN1 1LS',
    'footer.rights': '© 2024 MGL Digital Media LTD • Tüm Hakları Saklıdır',

    // Choice Section
    'choice.title': 'İşletmenizi Bir Sonraki Seviyeye Nasıl Taşımak İstersiniz?',
    'choice.subtitle': 'Size en uygun çözümü bulmamız için lütfen mevcut önceliğinizi seçin.',
    'choice.automation.title': 'Manuel İşleri Otomatikleştirin',
    'choice.automation.desc': 'Tekrarlayan görevleri, raporlamayı ve veri girişini akıllı asistanlara devrederek ekibinizin gerçekten önemli işlere odaklanmasını sağlayın.',
    'choice.automation.cta': 'Verimliliği Seç',
    'choice.customers.title': 'Müşteri Akışını Hızlandırın',
    'choice.customers.desc': 'Mevcut reklam kampanyalarınızdan daha iyi sonuçlar alın. Yapay zeka destekli stratejilerle reklam harcamanızın geri dönüşünü (ROAS) katlayın.',
    'choice.customers.cta': 'Daha Fazla Müşteri',
    'choice.system.title': 'Uçtan Uca Büyüme Motoru Kurun',
    'choice.system.desc': 'Reklamlarla getirdiğimiz potansiyel müşterileri, AI asistanlarla 7/24 takip edip satışa hazır hale getiren kusursuz bir sistem inşa edelim.',
    'choice.system.cta': 'Tüm Hikayeyi Gör',

    // Strategy Section
    'strategy.title': 'Başarı Tesadüf Değildir.',
    'strategy.subtitle': 'Her adımı ölçülebilir veriye dayanan, kanıtlanmış bir stratejiyle hareket ediyoruz.',
    'strategy.funnel': 'Funnel Stratejimiz',
    'strategy.kpi': 'KPI Takibimiz',
    'strategy.awareness.title': 'Farkındalık (TOF)',
    'strategy.awareness.psychology': 'Psikoloji:',
    'strategy.awareness.psychology.desc': 'Kullanıcı henüz sorununun farkında değil veya yeni fark etmiş. Amaç, dikkatini çekmek ve merak uyandırmak.',
    'strategy.awareness.approach': 'Yaklaşım:',
    'strategy.awareness.approach.desc': 'Markanızı/çözümünüzü tanıtan, soğuk kitleyi ısındıran, empati ve merak tetikleyici içerikler üretiriz.',
    'strategy.consideration.title': 'Değerlendirme (MOF)',
    'strategy.consideration.psychology': 'Psikoloji:',
    'strategy.consideration.psychology.desc': 'Artık sorunu kabul etti, çözüm alternatiflerini araştırıyor ve markaları kıyaslıyor.',
    'strategy.consideration.approach': 'Yaklaşım:',
    'strategy.consideration.approach.desc': 'Uzmanlığınızı ve güvenilirliğinizi gösteren, şeffaf içerikler sunarız.',
    'strategy.decision.title': 'Karar (BOF)',
    'strategy.decision.psychology': 'Psikoloji:',
    'strategy.decision.psychology.desc': 'Satın almaya çok yakın; son itici güç ve "doğrulama" arıyor.',
    'strategy.decision.approach': 'Yaklaşım:',
    'strategy.decision.approach.desc': 'Aciliyet ve sosyal kanıt vurgusu yapan reklamlarla kullanıcıyı dönüşüme yönlendiririz.',
    'strategy.cpm.title': 'CPM & Reach',
    'strategy.cpm.desc': 'CPM (1000 Gösterim Maliyeti) ve Reach (Erişim) metrikleriyle hedefleme kalitemizi ve kitleye ne kadar etkin ulaştığımızı ölçeriz.',
    'strategy.ctr.title': 'CTR & CPC',
    'strategy.ctr.desc': 'CTR (Tıklama Oranı) ile içeriğinizin ne kadar ilgi çekici olduğunu, CPC (Tıklama Başı Maliyet) ile de reklam verimliliğini anlık olarak takip ederiz.',
    'strategy.cpl.title': 'CPL & ROAS',
    'strategy.cpl.desc': 'CPL (Lead Başı Maliyet) ile her bir potansiyel müşterinin size maliyetini hesaplarız. En önemlisi, ROAS (Reklam Harcaması Geri Dönüşü) ile harcadığınız her liranın size ne kadar kazandırdığını net bir şekilde raporlarız.',

    // Success/Cancel Pages
    'success.title': 'Ödeme Başarılı!',
    'success.subtitle': 'Teşekkürler! Otomasyon çözümünüz için ödemeniz başarıyla alındı.',
    'success.order.title': 'Sipariş Detayları',
    'success.product': 'Ürün:',
    'success.amount': 'Tutar:',
    'success.status': 'Durum:',
    'success.completed': 'Tamamlandı',
    'success.next.title': 'Sırada Ne Var?',
    'success.next.contact': '• Ekibimiz 24 saat içinde sizinle iletişime geçecek',
    'success.next.details': '• Proje detayları ve timeline belirlenir',
    'success.next.setup': '• Otomasyon sisteminiz kurulur ve test edilir',
    'success.next.training': '• Eğitim ve devreye alma süreci tamamlanır',
    'success.back': 'Ana Sayfaya Dön',
    'success.whatsapp': 'WhatsApp ile İletişime Geç',
    'cancel.title': 'Ödeme İptal Edildi',
    'cancel.subtitle': 'Ödeme işlemi iptal edildi. Herhangi bir ücret tahsil edilmedi.',
    'cancel.help.title': 'Yardıma mı İhtiyacınız Var?',
    'cancel.help.desc': 'Ödeme sürecinde sorun yaşıyorsanız, doğrudan bizimle iletişime geçebilirsiniz.',
    'cancel.back': 'Ana Sayfaya Dön',
    'cancel.retry': 'Tekrar Dene',
    'cancel.support': 'WhatsApp ile Destek Al',

    // Subscription Status
    'subscription.active': 'Aktif Abonelik',
    'subscription.products': 'Satın Alınan Ürünler',
    'subscription.active.desc': 'Aktif',
    'subscription.products.desc': 'ürün satın alındı',

    // Modals
    'modal.email.title': 'Otomatik E-posta Demo',
    'modal.email.desc': 'Bu formu doldurun ve e-posta otomasyonunun nasıl başladığını görün.',
    'modal.email.name': 'Adınız',
    'modal.email.name.placeholder': 'Örn: Ahmet Yılmaz',
    'modal.email.email': 'E-posta Adresiniz',
    'modal.email.email.placeholder': 'ornek@email.com',
    'modal.email.start': 'Otomasyonu Başlat',
    'modal.email.success.title': 'Harika, {name}!',
    'modal.email.success.desc': 'Otomasyonunuz başarıyla başlatıldı. İlk e-postamız gelen kutunuza ulaştı bile. Cevap verdiğinizde AI asistanımızla fikirler geliştirebilirsiniz.',
    'modal.email.success.button': 'Harika!',
    'modal.phone.title': 'AI Sesli Asistan Demo',
    'modal.phone.desc': 'AI sesli asistanımızın yeteneklerini test etmek için telefon numaranızı girin, sizi arayalım.',
    'modal.phone.placeholder': '555 123 4567',
    'modal.phone.button': 'AI Beni Arasın',
    'modal.phone.success.title': 'Çağrı İsteğiniz Alındı!',
    'modal.phone.success.desc': 'AI asistanımız +44 (7414) 605612 numaralı hattan sizi arayacak. Lütfen telefonunuzu kontrol edin.',
    'modal.phone.success.button': 'Kapat',
    'modal.idea.generating': 'AI sizin için fikir üretiyor...',
    'modal.idea.industry': 'Merhaba! İşletmeniz için otomasyon potansiyelini keşfedelim. Hangi sektörde faaliyet gösteriyorsunuz?',
    'modal.idea.painpoint': 'Harika, {industry}. Peki en çok hangi alanda zaman kazanmak veya süreci iyileştirmek istersiniz?',
    'modal.idea.custom': 'Lütfen otomatikleştirmek istediğiniz süreci kısaca açıklayın:',
    'modal.idea.custom.placeholder': 'Örn: Gelen faturaları işlemek',
    'modal.idea.send': 'Gönder',
    'modal.idea.result': 'Anladım. {painPoint} konusunda size yardımcı olabiliriz. İşte AI tarafından üretilen bir fikir:',
    'modal.idea.newIdea': 'Yeni Fikir Üret',
    'modal.idea.restart': 'Baştan Başla',
    'modal.idea.contact': 'Bu sadece bir mini demo! Gerçek projeleriniz için bizimle iletişime geçebilirsiniz.',
    'modal.idea.great': 'Harika!',
    'modal.idea.error': 'AI asistanımız anlık bir yoğunluk yaşıyor ve size özel bir fikir üretemedi.',
    'modal.idea.error.demo': 'Bu sırada, otomasyonun gücünü görmek için canlı demolarımızı deneyebilirsiniz.',
    'modal.idea.error.button': 'Canlı Demoları Gör',

    // Toast Messages
    'toast.success': 'Başarılı!',
    'toast.error': 'Hata!',
    'toast.info': 'Bilgi',
    'toast.warning': 'Uyarı',
    'toast.request.sent': 'İstek Gönderildi! 🚀',
    'toast.request.sent.desc': 'Bilgileriniz iş akışına başarıyla iletildi.',
    'toast.workflow.error': 'İş akışına bağlanırken bir sorun oluştu.',
    'toast.phone.success': 'Harika!',
    'toast.phone.success.desc': 'AI asistanımız belirttiğiniz numarayı arayacak.',
    'toast.idea.success': 'Harika!',
    'toast.idea.success.desc': 'Detaylı analiz en kısa sürede e-posta adresinize gönderilecektir.',
    'toast.idea.error': 'Bir sorun oluştu, lütfen daha sonra tekrar deneyin.',
    'toast.checkout.error': 'Ödeme Hatası',
    'toast.checkout.error.desc': 'Ödeme sayfası açılırken bir hata oluştu. Lütfen tekrar deneyin.',
    'toast.connection.error': 'Bağlantı Hatası',
    'toast.connection.error.desc': 'Chatbot servisi şu anda kullanılamıyor. Lütfen daha sonra tekrar deneyin.',
    'toast.invalid.phone': 'Geçersiz Numara',
    'toast.invalid.phone.desc': 'Lütfen geçerli bir telefon numarası girin.',
    'toast.missing.info': 'Eksik Bilgi',
    'toast.missing.info.desc': 'Lütfen tüm alanları doldurun.',
    'toast.password.mismatch': 'Şifre Uyumsuzluğu',
    'toast.password.mismatch.desc': 'Şifreler eşleşmiyor.',
    'toast.weak.password': 'Zayıf Şifre',
    'toast.weak.password.desc': 'Şifre en az 6 karakter olmalıdır.',
    'toast.email.required': 'E-posta Gerekli',
    'toast.email.required.desc': 'Şifre sıfırlama için e-posta adresinizi girin.',
    'toast.reset.sent': 'E-posta Gönderildi',
    'toast.reset.sent.desc': 'Şifre sıfırlama bağlantısı e-posta adresinize gönderildi.',
    'toast.login.error': 'Giriş Hatası',
    'toast.login.error.desc': 'E-posta veya şifre hatalı.',
    'toast.signup.error': 'Kayıt Hatası',
    'toast.signup.error.desc': 'Kayıt olurken bir hata oluştu.',
    'toast.email.exists': 'E-posta Zaten Kayıtlı',
    'toast.email.exists.desc': 'Bu e-posta adresi zaten kayıtlı. Giriş sayfasına yönlendiriliyorsunuz...',

    // Common
    'common.close': 'Kapat',
    'common.cancel': 'İptal',
    'common.save': 'Kaydet',
    'common.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.loading': 'Yükleniyor...',
    'common.error': 'Hata',
    'common.success': 'Başarılı',
    'common.warning': 'Uyarı',
    'common.info': 'Bilgi',
    'common.yes': 'Evet',
    'common.no': 'Hayır',
    'common.ok': 'Tamam',
    'common.back': 'Geri',
    'common.next': 'İleri',
    'common.previous': 'Önceki',
    'common.continue': 'Devam Et',
    'common.finish': 'Bitir',
    'common.submit': 'Gönder',
    'common.search': 'Ara',
    'common.filter': 'Filtrele',
    'common.sort': 'Sırala',
    'common.view': 'Görüntüle',
    'common.download': 'İndir',
    'common.upload': 'Yükle',
    'common.share': 'Paylaş',
    'common.copy': 'Kopyala',
    'common.paste': 'Yapıştır',
    'common.cut': 'Kes',
    'common.undo': 'Geri Al',
    'common.redo': 'Yinele',
    'common.refresh': 'Yenile',
    'common.reload': 'Yeniden Yükle',
    'common.print': 'Yazdır',
    'common.help': 'Yardım',
    'common.about': 'Hakkında',
    'common.contact': 'İletişim',
    'common.privacy': 'Gizlilik',
    'common.terms': 'Şartlar',
    'common.settings': 'Ayarlar',
    'common.profile': 'Profil',
    'common.account': 'Hesap',
    'common.dashboard': 'Panel',
    'common.home': 'Ana Sayfa',
    'common.menu': 'Menü',
    'common.more': 'Daha Fazla',
    'common.less': 'Daha Az',
    'common.show': 'Göster',
    'common.hide': 'Gizle',
    'common.expand': 'Genişlet',
    'common.collapse': 'Daralt',
    'common.select': 'Seç',
    'common.deselect': 'Seçimi Kaldır',
    'common.selectAll': 'Tümünü Seç',
    'common.deselectAll': 'Tüm Seçimi Kaldır',
    'common.add': 'Ekle',
    'common.remove': 'Kaldır',
    'common.create': 'Oluştur',
    'common.update': 'Güncelle',
    'common.modify': 'Değiştir',
    'common.change': 'Değiştir',
    'common.replace': 'Değiştir',
    'common.duplicate': 'Kopyala',
    'common.move': 'Taşı',
    'common.rename': 'Yeniden Adlandır',
    'common.import': 'İçe Aktar',
    'common.export': 'Dışa Aktar',
    'common.backup': 'Yedekle',
    'common.restore': 'Geri Yükle',
    'common.reset': 'Sıfırla',
    'common.clear': 'Temizle',
    'common.empty': 'Boş',
    'common.full': 'Dolu',
    'common.available': 'Mevcut',
    'common.unavailable': 'Mevcut Değil',
    'common.online': 'Çevrimiçi',
    'common.offline': 'Çevrimdışı',
    'common.connected': 'Bağlı',
    'common.disconnected': 'Bağlantı Kesildi',
    'common.active': 'Aktif',
    'common.inactive': 'Pasif',
    'common.enabled': 'Etkin',
    'common.disabled': 'Devre Dışı',
    'common.public': 'Genel',
    'common.private': 'Özel',
    'common.visible': 'Görünür',
    'common.hidden': 'Gizli',
    'common.required': 'Gerekli',
    'common.optional': 'İsteğe Bağlı',
    'common.recommended': 'Önerilen',
    'common.popular': 'Popüler',
    'common.featured': 'Öne Çıkan',
    'common.new': 'Yeni',
    'common.updated': 'Güncellendi',
    'common.latest': 'En Son',
    'common.recent': 'Son',
    'common.old': 'Eski',
    'common.archived': 'Arşivlendi',
    'common.deleted': 'Silindi',
    'common.draft': 'Taslak',
    'common.published': 'Yayınlandı',
    'common.pending': 'Beklemede',
    'common.approved': 'Onaylandı',
    'common.rejected': 'Reddedildi',
    'common.completed': 'Tamamlandı',
    'common.failed': 'Başarısız',
    'common.cancelled': 'İptal Edildi',
    'common.expired': 'Süresi Doldu',
    'common.valid': 'Geçerli',
    'common.invalid': 'Geçersiz',
    'common.correct': 'Doğru',
    'common.incorrect': 'Yanlış',
    'common.true': 'Doğru',
    'common.false': 'Yanlış',
    'common.on': 'Açık',
    'common.off': 'Kapalı',
    'common.high': 'Yüksek',
    'common.medium': 'Orta',
    'common.low': 'Düşük',
    'common.fast': 'Hızlı',
    'common.slow': 'Yavaş',
    'common.easy': 'Kolay',
    'common.hard': 'Zor',
    'common.simple': 'Basit',
    'common.complex': 'Karmaşık',
    'common.basic': 'Temel',
    'common.advanced': 'Gelişmiş',
    'common.professional': 'Profesyonel',
    'common.premium': 'Premium',
    'common.free': 'Ücretsiz',
    'common.paid': 'Ücretli',
    'common.trial': 'Deneme',
    'common.demo': 'Demo',
    'common.beta': 'Beta',
    'common.alpha': 'Alfa',
    'common.stable': 'Kararlı',
    'common.unstable': 'Kararsız',
    'common.secure': 'Güvenli',
    'common.insecure': 'Güvensiz',
    'common.safe': 'Güvenli',
    'common.unsafe': 'Güvensiz',
    'common.clean': 'Temiz',
    'common.dirty': 'Kirli',
    'common.fresh': 'Taze',
    'common.stale': 'Bayat',
    'common.hot': 'Sıcak',
    'common.cold': 'Soğuk',
    'common.warm': 'Ilık',
    'common.cool': 'Serin',
    'common.bright': 'Parlak',
    'common.dark': 'Karanlık',
    'common.light': 'Açık',
    'common.heavy': 'Ağır',
    'common.big': 'Büyük',
    'common.small': 'Küçük',
    'common.large': 'Büyük',
    'common.tiny': 'Minik',
    'common.huge': 'Devasa',
    'common.wide': 'Geniş',
    'common.narrow': 'Dar',
    'common.thick': 'Kalın',
    'common.thin': 'İnce',
    'common.long': 'Uzun',
    'common.short': 'Kısa',
    'common.tall': 'Uzun',
    'common.deep': 'Derin',
    'common.shallow': 'Sığ',
    'common.round': 'Yuvarlak',
    'common.square': 'Kare',
    'common.flat': 'Düz',
    'common.curved': 'Kavisli',
    'common.straight': 'Düz',
    'common.smooth': 'Pürüzsüz',
    'common.rough': 'Pürüzlü',
    'common.soft': 'Yumuşak',
    'common.hard': 'Sert',
    'common.solid': 'Katı',
    'common.liquid': 'Sıvı',
    'common.gas': 'Gaz',
    'common.transparent': 'Şeffaf',
    'common.opaque': 'Mat',
    'common.clear': 'Berrak',
    'common.blurry': 'Bulanık',
    'common.sharp': 'Keskin',
    'common.dull': 'Körelmiş',
    'common.shiny': 'Parlak',
    'common.matte': 'Mat',
    'common.glossy': 'Parlak',
    'common.metallic': 'Metalik',
    'common.wooden': 'Ahşap',
    'common.plastic': 'Plastik',
    'common.glass': 'Cam',
    'common.paper': 'Kağıt',
    'common.fabric': 'Kumaş',
    'common.leather': 'Deri',
    'common.rubber': 'Kauçuk',
    'common.stone': 'Taş',
    'common.concrete': 'Beton',
    'common.brick': 'Tuğla',
    'common.ceramic': 'Seramik',
    'common.porcelain': 'Porselen',
    'common.crystal': 'Kristal',
    'common.diamond': 'Elmas',
    'common.gold': 'Altın',
    'common.silver': 'Gümüş',
    'common.copper': 'Bakır',
    'common.iron': 'Demir',
    'common.steel': 'Çelik',
    'common.aluminum': 'Alüminyum',
    'common.titanium': 'Titanyum',
    'common.carbon': 'Karbon',
    'common.silicon': 'Silikon',
    'common.oxygen': 'Oksijen',
    'common.hydrogen': 'Hidrojen',
    'common.nitrogen': 'Azot',
    'common.helium': 'Helyum',
    'common.neon': 'Neon',
    'common.argon': 'Argon',
    'common.krypton': 'Kripton',
    'common.xenon': 'Ksenon',
    'common.radon': 'Radon',

    // Product Features
    'products.feature.custom': 'Size özel tasarım',
    'products.feature.setup': 'Profesyonel kurulum',
    'products.feature.support': 'Teknik destek',
  },
  en: {
    // Header
    'header.title': 'MGL Digital AI',
    'header.login': 'Login / Register',
    'header.logout': 'Logout',
    'header.opportunities': 'Discover Opportunities',
    'header.welcome': 'Welcome',

    // Hero Section
    'hero.title': 'We Drive Transformation Through Strategy.',
    'hero.subtitle': 'By automating your advertising and business processes with AI Agents. We bring real "results", not just "clicks".',
    'hero.cta.opportunities': 'Discover Opportunities with AI',
    'hero.cta.demos': 'See Live Demos',

    // Benefits Section
    'benefits.title': 'Not Just Working, But Working Smart',
    'benefits.subtitle': 'Tired of doing the same tasks over and over every day? Here are solutions that will save you time, money, and customers:',
    'benefits.time.title': 'Time Savings',
    'benefits.time.desc': 'Get rid of 3-4 hours of manual work per day',
    'benefits.sales.title': 'Sales Increase',
    'benefits.sales.desc': 'Capture 40% more sales with automatic follow-up',
    'benefits.error.title': 'Error Reduction',
    'benefits.error.desc': 'Human error drops to zero, everything works perfectly',
    'benefits.satisfaction.title': 'Customer Satisfaction',
    'benefits.satisfaction.desc': 'Create happy customers with 24/7 instant response',

    // Services Section
    'services.title': 'One Center, Unlimited Capability',
    'services.subtitle': 'From strategy to design, from advertising to automation, we are here for all your digital needs.',
    'services.ads.title': 'AI-Powered Advertising Management',
    'services.ads.desc': 'We manage your Meta & Google ad campaigns with continuously learning artificial intelligence algorithms, using your budget most efficiently.',
    'services.ads.integration': 'We instantly meet every potential customer from ads with AI Chatbot or Voice Assistant.',
    'services.automation.title': 'AI Agent & Automation Setup',
    'services.automation.desc': 'We design smart assistants that work 24/7 for WhatsApp, Email, Phone and your website, making appointments, providing information and collecting data.',
    'services.automation.integration': 'We plan ad campaigns that bring the right prospects to feed the automations we set up.',
    'services.web.title': 'Conversion-Focused Web Design',
    'services.web.desc': 'We build modern and fast websites that work not only beautifully, but also as a customer acquisition machine.',
    'services.web.integration': 'We integrate interactive Live Demo modules and Chatbots into every site we design to convert your visitors into customers.',

    // Demos Section
    'demos.title': 'We Don\'t Tell, We Show.',
    'demos.subtitle': 'Try the demos below and think "I wonder if my work can be automated too?":',
    'demos.whatsapp.title': 'One-on-One Strategy Meeting',
    'demos.whatsapp.desc': 'Contact our founder Mustafa directly via WhatsApp to discuss your automation ideas.',
    'demos.email.title': 'Automatic Email Series',
    'demos.email.desc': 'Send a personalized email instantly to everyone who fills out the form on your website.',
    'demos.phone.title': 'Let AI Call You',
    'demos.phone.desc': 'Leave your number, let our AI voice assistant call you and showcase its capabilities.',
    'demos.contact': 'Get in Touch',
    'demos.live': 'Live Demo',
    'demos.data.title': 'Manual Data Transfer',
    'demos.data.desc': 'Are you constantly copying and pasting from Excel to CRM? Completely eliminate this process.',
    'demos.reports.title': 'Weekly Report Struggle',
    'demos.reports.desc': 'Does collecting data from different platforms and preparing reports every week take hours?',
    'demos.onboarding.title': 'New Employee Processes',
    'demos.onboarding.desc': 'Are you giving documents to new hires one by one? Start the entire process automatically with one click.',

    // Strategy Section
    'strategy.title': 'Success Is Not Coincidence.',
    'strategy.subtitle': 'We act with a proven strategy based on measurable data at every step.',
    'strategy.funnel': 'Our Funnel Strategy',
    'strategy.kpi': 'Our KPI Tracking',

    // CTA Section
    'cta.title': 'Ready? Let\'s Transform Your Business Together!',
    'cta.subtitle': 'Let us provide you with a 2-minute personalized analysis to learn which of your manual processes can be automated and how you can use your advertising budget more efficiently.',
    'cta.analysis': 'Get Free Automation Analysis',
    'cta.products': 'Buy Automation',

    // Products Page
    'products.title': 'Automation Solutions',
    'products.subtitle': 'AI automation systems specially designed for your business',
    'products.back': 'Back to Home',
    'products.buy': 'Buy Now',
    'products.subscribe': 'Start Subscription',

    // Auth
    'auth.login': 'Login to Your Account',
    'auth.signup': 'Create Account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Create Account',
    'auth.switchToSignup': 'Sign Up',
    'auth.switchToLogin': 'Login',
    'auth.forgotPassword': 'Forgot Password',

    // Chatbot
    'chatbot.title': 'AI Assistant',
    'chatbot.subtitle': 'Usually responds instantly',
    'chatbot.placeholder': 'Type your message...',
    'chatbot.greeting': 'Hello! How can I help you?',
    'chatbot.button': 'Try AI Chatbot',

    // Footer
    'footer.title': 'AI Automation Agency - Taking Your Business to the Future',
    'footer.company': 'MGL DIGITAL MEDIA LTD',
    'footer.registered': 'Registered in England and Wales. Company Number: 16007414',
    'footer.office': 'Registered Office',
    'footer.address': '112 Bertram Road, Enfield, England, EN1 1LS',
    'footer.rights': '© 2024 MGL Digital Media LTD • All Rights Reserved',

    // Choice Section
    'choice.title': 'How Would You Like to Take Your Business to the Next Level?',
    'choice.subtitle': 'Please select your current priority so we can find the most suitable solution for you.',
    'choice.automation.title': 'Automate Manual Tasks',
    'choice.automation.desc': 'Enable your team to focus on truly important tasks by delegating repetitive tasks, reporting and data entry to smart assistants.',
    'choice.automation.cta': 'Choose Efficiency',
    'choice.customers.title': 'Accelerate Customer Flow',
    'choice.customers.desc': 'Get better results from your existing advertising campaigns. Multiply your return on ad spend (ROAS) with AI-powered strategies.',
    'choice.customers.cta': 'More Customers',
    'choice.system.title': 'Build End-to-End Growth Engine',
    'choice.system.desc': 'Let\'s build a perfect system that follows up potential customers brought by ads with AI assistants 24/7 and makes them ready for sales.',
    'choice.system.cta': 'See the Full Story',

    // Strategy Section
    'strategy.title': 'Success Is Not Coincidence.',
    'strategy.subtitle': 'We act with a proven strategy based on measurable data at every step.',
    'strategy.funnel': 'Our Funnel Strategy',
    'strategy.kpi': 'Our KPI Tracking',
    'strategy.awareness.title': 'Awareness (TOF)',
    'strategy.awareness.psychology': 'Psychology:',
    'strategy.awareness.psychology.desc': 'User is not yet aware of their problem or has just realized it. The goal is to attract attention and arouse curiosity.',
    'strategy.awareness.approach': 'Approach:',
    'strategy.awareness.approach.desc': 'We produce content that introduces your brand/solution, warms up cold audiences, and triggers empathy and curiosity.',
    'strategy.consideration.title': 'Consideration (MOF)',
    'strategy.consideration.psychology': 'Psychology:',
    'strategy.consideration.psychology.desc': 'Now they have accepted the problem, are researching solution alternatives and comparing brands.',
    'strategy.consideration.approach': 'Approach:',
    'strategy.consideration.approach.desc': 'We offer transparent content that shows your expertise and reliability.',
    'strategy.decision.title': 'Decision (BOF)',
    'strategy.decision.psychology': 'Psychology:',
    'strategy.decision.psychology.desc': 'Very close to purchasing; looking for final push and "validation".',
    'strategy.decision.approach': 'Approach:',
    'strategy.decision.approach.desc': 'We direct users to conversion with ads that emphasize urgency and social proof.',
    'strategy.cpm.title': 'CPM & Reach',
    'strategy.cpm.desc': 'We measure our targeting quality and how effectively we reach the audience with CPM (Cost Per 1000 Impressions) and Reach metrics.',
    'strategy.ctr.title': 'CTR & CPC',
    'strategy.ctr.desc': 'We track how engaging your content is with CTR (Click Through Rate) and advertising efficiency with CPC (Cost Per Click) in real time.',
    'strategy.cpl.title': 'CPL & ROAS',
    'strategy.cpl.desc': 'We calculate the cost of each potential customer to you with CPL (Cost Per Lead). Most importantly, we clearly report how much each lira you spend earns you with ROAS (Return on Ad Spend).',

    // Success/Cancel Pages
    'success.title': 'Payment Successful!',
    'success.subtitle': 'Thank you! Your payment for the automation solution has been successfully received.',
    'success.order.title': 'Order Details',
    'success.product': 'Product:',
    'success.amount': 'Amount:',
    'success.status': 'Status:',
    'success.completed': 'Completed',
    'success.next.title': 'What\'s Next?',
    'success.next.contact': '• Our team will contact you within 24 hours',
    'success.next.details': '• Project details and timeline will be determined',
    'success.next.setup': '• Your automation system will be set up and tested',
    'success.next.training': '• Training and deployment process will be completed',
    'success.back': 'Back to Home',
    'success.whatsapp': 'Contact via WhatsApp',
    'cancel.title': 'Payment Cancelled',
    'cancel.subtitle': 'Payment process was cancelled. No charges were made.',
    'cancel.help.title': 'Need Help?',
    'cancel.help.desc': 'If you\'re experiencing issues with the payment process, you can contact us directly.',
    'cancel.back': 'Back to Home',
    'cancel.retry': 'Try Again',
    'cancel.support': 'Get Support via WhatsApp',

    // Subscription Status
    'subscription.active': 'Active Subscription',
    'subscription.products': 'Purchased Products',
    'subscription.active.desc': 'Active',
    'subscription.products.desc': 'products purchased',

    // Modals
    'modal.email.title': 'Automatic Email Demo',
    'modal.email.desc': 'Fill out this form and see how email automation starts.',
    'modal.email.name': 'Your Name',
    'modal.email.name.placeholder': 'e.g. John Doe',
    'modal.email.email': 'Your Email Address',
    'modal.email.email.placeholder': 'example@email.com',
    'modal.email.start': 'Start Automation',
    'modal.email.success.title': 'Great, {name}!',
    'modal.email.success.desc': 'Your automation has been successfully started. Our first email has already reached your inbox. When you reply, you can develop ideas with our AI assistant.',
    'modal.email.success.button': 'Great!',
    'modal.phone.title': 'AI Voice Assistant Demo',
    'modal.phone.desc': 'Enter your phone number to test our AI voice assistant\'s capabilities, let us call you.',
    'modal.phone.placeholder': '555 123 4567',
    'modal.phone.button': 'Let AI Call Me',
    'modal.phone.success.title': 'Call Request Received!',
    'modal.phone.success.desc': 'Our AI assistant will call you from +44 (7414) 605612. Please check your phone.',
    'modal.phone.success.button': 'Close',
    'modal.idea.generating': 'AI is generating ideas for you...',
    'modal.idea.industry': 'Hello! Let\'s discover the automation potential for your business. Which sector do you operate in?',
    'modal.idea.painpoint': 'Great, {industry}. So in which area would you most like to save time or improve processes?',
    'modal.idea.custom': 'Please briefly describe the process you want to automate:',
    'modal.idea.custom.placeholder': 'e.g. Processing incoming invoices',
    'modal.idea.send': 'Send',
    'modal.idea.result': 'I understand. We can help you with {painPoint}. Here\'s an idea generated by AI:',
    'modal.idea.newIdea': 'Generate New Idea',
    'modal.idea.restart': 'Start Over',
    'modal.idea.contact': 'This is just a mini demo! You can contact us for your real projects.',
    'modal.idea.great': 'Great!',
    'modal.idea.error': 'Our AI assistant is experiencing momentary high traffic and couldn\'t generate a custom idea for you.',
    'modal.idea.error.demo': 'Meanwhile, you can try our live demos to see the power of automation.',
    'modal.idea.error.button': 'See Live Demos',

    // Toast Messages
    'toast.success': 'Success!',
    'toast.error': 'Error!',
    'toast.info': 'Info',
    'toast.warning': 'Warning',
    'toast.request.sent': 'Request Sent! 🚀',
    'toast.request.sent.desc': 'Your information has been successfully sent to the workflow.',
    'toast.workflow.error': 'A problem occurred while connecting to the workflow.',
    'toast.phone.success': 'Great!',
    'toast.phone.success.desc': 'Our AI assistant will call the number you specified.',
    'toast.idea.success': 'Great!',
    'toast.idea.success.desc': 'Detailed analysis will be sent to your email address as soon as possible.',
    'toast.idea.error': 'A problem occurred, please try again later.',
    'toast.checkout.error': 'Payment Error',
    'toast.checkout.error.desc': 'An error occurred while opening the payment page. Please try again.',
    'toast.connection.error': 'Connection Error',
    'toast.connection.error.desc': 'Chatbot service is currently unavailable. Please try again later.',
    'toast.invalid.phone': 'Invalid Number',
    'toast.invalid.phone.desc': 'Please enter a valid phone number.',
    'toast.missing.info': 'Missing Information',
    'toast.missing.info.desc': 'Please fill in all fields.',
    'toast.password.mismatch': 'Password Mismatch',
    'toast.password.mismatch.desc': 'Passwords do not match.',
    'toast.weak.password': 'Weak Password',
    'toast.weak.password.desc': 'Password must be at least 6 characters.',
    'toast.email.required': 'Email Required',
    'toast.email.required.desc': 'Enter your email address for password reset.',
    'toast.reset.sent': 'Email Sent',
    'toast.reset.sent.desc': 'Password reset link has been sent to your email address.',
    'toast.login.error': 'Login Error',
    'toast.login.error.desc': 'Email or password is incorrect.',
    'toast.signup.error': 'Registration Error',
    'toast.signup.error.desc': 'An error occurred during registration.',
    'toast.email.exists': 'Email Already Registered',
    'toast.email.exists.desc': 'This email address is already registered. Redirecting to login page...',

    // Common
    'common.close': 'Close',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.continue': 'Continue',
    'common.finish': 'Finish',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.view': 'View',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.share': 'Share',
    'common.copy': 'Copy',
    'common.paste': 'Paste',
    'common.cut': 'Cut',
    'common.undo': 'Undo',
    'common.redo': 'Redo',
    'common.refresh': 'Refresh',
    'common.reload': 'Reload',
    'common.print': 'Print',
    'common.help': 'Help',
    'common.about': 'About',
    'common.contact': 'Contact',
    'common.privacy': 'Privacy',
    'common.terms': 'Terms',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.account': 'Account',
    'common.dashboard': 'Dashboard',
    'common.home': 'Home',
    'common.menu': 'Menu',
    'common.more': 'More',
    'common.less': 'Less',
    'common.show': 'Show',
    'common.hide': 'Hide',
    'common.expand': 'Expand',
    'common.collapse': 'Collapse',
    'common.select': 'Select',
    'common.deselect': 'Deselect',
    'common.selectAll': 'Select All',
    'common.deselectAll': 'Deselect All',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.modify': 'Modify',
    'common.change': 'Change',
    'common.replace': 'Replace',
    'common.duplicate': 'Duplicate',
    'common.move': 'Move',
    'common.rename': 'Rename',
    'common.import': 'Import',
    'common.export': 'Export',
    'common.backup': 'Backup',
    'common.restore': 'Restore',
    'common.reset': 'Reset',
    'common.clear': 'Clear',
    'common.empty': 'Empty',
    'common.full': 'Full',
    'common.available': 'Available',
    'common.unavailable': 'Unavailable',
    'common.online': 'Online',
    'common.offline': 'Offline',
    'common.connected': 'Connected',
    'common.disconnected': 'Disconnected',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.public': 'Public',
    'common.private': 'Private',
    'common.visible': 'Visible',
    'common.hidden': 'Hidden',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.recommended': 'Recommended',
    'common.popular': 'Popular',
    'common.featured': 'Featured',
    'common.new': 'New',
    'common.updated': 'Updated',
    'common.latest': 'Latest',
    'common.recent': 'Recent',
    'common.old': 'Old',
    'common.archived': 'Archived',
    'common.deleted': 'Deleted',
    'common.draft': 'Draft',
    'common.published': 'Published',
    'common.pending': 'Pending',
    'common.approved': 'Approved',
    'common.rejected': 'Rejected',
    'common.completed': 'Completed',
    'common.failed': 'Failed',
    'common.cancelled': 'Cancelled',
    'common.expired': 'Expired',
    'common.valid': 'Valid',
    'common.invalid': 'Invalid',
    'common.correct': 'Correct',
    'common.incorrect': 'Incorrect',
    'common.true': 'True',
    'common.false': 'False',
    'common.on': 'On',
    'common.off': 'Off',
    'common.high': 'High',
    'common.medium': 'Medium',
    'common.low': 'Low',
    'common.fast': 'Fast',
    'common.slow': 'Slow',
    'common.easy': 'Easy',
    'common.hard': 'Hard',
    'common.simple': 'Simple',
    'common.complex': 'Complex',
    'common.basic': 'Basic',
    'common.advanced': 'Advanced',
    'common.professional': 'Professional',
    'common.premium': 'Premium',
    'common.free': 'Free',
    'common.paid': 'Paid',
    'common.trial': 'Trial',
    'common.demo': 'Demo',
    'common.beta': 'Beta',
    'common.alpha': 'Alpha',
    'common.stable': 'Stable',
    'common.unstable': 'Unstable',
    'common.secure': 'Secure',
    'common.insecure': 'Insecure',
    'common.safe': 'Safe',
    'common.unsafe': 'Unsafe',
    'common.clean': 'Clean',
    'common.dirty': 'Dirty',
    'common.fresh': 'Fresh',
    'common.stale': 'Stale',
    'common.hot': 'Hot',
    'common.cold': 'Cold',
    'common.warm': 'Warm',
    'common.cool': 'Cool',
    'common.bright': 'Bright',
    'common.dark': 'Dark',
    'common.light': 'Light',
    'common.heavy': 'Heavy',
    'common.big': 'Big',
    'common.small': 'Small',
    'common.large': 'Large',
    'common.tiny': 'Tiny',
    'common.huge': 'Huge',
    'common.wide': 'Wide',
    'common.narrow': 'Narrow',
    'common.thick': 'Thick',
    'common.thin': 'Thin',
    'common.long': 'Long',
    'common.short': 'Short',
    'common.tall': 'Tall',
    'common.deep': 'Deep',
    'common.shallow': 'Shallow',
    'common.round': 'Round',
    'common.square': 'Square',
    'common.flat': 'Flat',
    'common.curved': 'Curved',
    'common.straight': 'Straight',
    'common.smooth': 'Smooth',
    'common.rough': 'Rough',
    'common.soft': 'Soft',
    'common.hard': 'Hard',
    'common.solid': 'Solid',
    'common.liquid': 'Liquid',
    'common.gas': 'Gas',
    'common.transparent': 'Transparent',
    'common.opaque': 'Opaque',
    'common.clear': 'Clear',
    'common.blurry': 'Blurry',
    'common.sharp': 'Sharp',
    'common.dull': 'Dull',
    'common.shiny': 'Shiny',
    'common.matte': 'Matte',
    'common.glossy': 'Glossy',
    'common.metallic': 'Metallic',
    'common.wooden': 'Wooden',
    'common.plastic': 'Plastic',
    'common.glass': 'Glass',
    'common.paper': 'Paper',
    'common.fabric': 'Fabric',
    'common.leather': 'Leather',
    'common.rubber': 'Rubber',
    'common.stone': 'Stone',
    'common.concrete': 'Concrete',
    'common.brick': 'Brick',
    'common.ceramic': 'Ceramic',
    'common.porcelain': 'Porcelain',
    'common.crystal': 'Crystal',
    'common.diamond': 'Diamond',
    'common.gold': 'Gold',
    'common.silver': 'Silver',
    'common.copper': 'Copper',
    'common.iron': 'Iron',
    'common.steel': 'Steel',
    'common.aluminum': 'Aluminum',
    'common.titanium': 'Titanium',
    'common.carbon': 'Carbon',
    'common.silicon': 'Silicon',
    'common.oxygen': 'Oxygen',
    'common.hydrogen': 'Hydrogen',
    'common.nitrogen': 'Nitrogen',
    'common.helium': 'Helium',
    'common.neon': 'Neon',
    'common.argon': 'Argon',
    'common.krypton': 'Krypton',
    'common.xenon': 'Xenon',
    'common.radon': 'Radon',

    // Product Features
    'products.feature.custom': 'Custom design for you',
    'products.feature.setup': 'Professional setup',
    'products.feature.support': 'Technical support',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'tr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
};